# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
