# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-15 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_comment_rev_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='review_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='review.Review'),
            preserve_default=False,
        ),
    ]
