# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-24 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180324_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Gym',
        ),
    ]
