# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-24 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180324_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='gym_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Gym'),
        ),
    ]
