# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180324_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='gym_id',
        ),
    ]
