# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180325_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='timing',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
