# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180403_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='timing',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
