# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180403_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='id',
        ),
        migrations.RemoveField(
            model_name='content_long',
            name='id',
        ),
        migrations.AlterField(
            model_name='address',
            name='gym_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.Gym'),
        ),
        migrations.AlterField(
            model_name='content_long',
            name='gym_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.Gym'),
        ),
    ]
